source 'http://rubygems.org'

#gem 'activesupport', '3.0.0'
gem 'capybara', '~> 0.4.1'
gem 'capybara-mechanize'
gem 'capybara-webkit'
gem 'cucumber'
gem 'headless'
gem 'jasmine'
gem 'i18n'
gem 'jasmine'
gem 'launchy'
gem 'Selenium'
gem 'selenium-client'
gem 'selenium-webdriver'
gem 'xpath'
gem 'rspec'
